### ISSUE TITLE
Lesson 2 - Problem 7

### ISSUE THREAD

**Issue by Spencerbrucehudson** [pearselab/r-intro-Spencerbrucehudson#3]
Hi Dr. Pearse,

On number 7, you're asking to set colors for values of Y above A and B. In playing with the model, is there ever an instance when Y is actually above A? If so, what parameter values should I use? Y always seems to be approaching A and in some circumstances, equal to A, but never above A. As such, I'm left with only one color (red) for the graph (those that were above B)

**Comment by willpearse** [comment]
There aren't any! Sometimes your code works perfectly, but the thing you're trying to do doesn't make any sense. Not everyone has figured this out yet - well done!

**Comment by Spencerbrucehudson** [comment]
Okay great.

Thanks!
