### ISSUE TITLE
Making A Box

### ISSUE THREAD

**Issue by Spencerbrucehudson** [pearselab/r-intro-Spencerbrucehudson#4]
After hours of working on Lesson 2, # 9, I didn't think I could ever make a box, but I did. Could you take a look at this code and tell me if this is similar to what you were looking for?

**Comment by willpearse** [comment]
This is fantastic: well done!!! Please don't comment issues so shortly after making them - thanks to time zones I was asleep when you opened this :-(

Two suggestions:
- Call your different box functions different names. That way it's easier to run each of them without having to re-load the code for the previous function
- You're having a bit of trouble with question 10 and 11 with text that's of an even length (I've put an example below). If you're looking for an easy fix, take a quick look at whether making the borders without spaces (e.g., `*******` not `* * * * *`) will help make that easier.

WELL DONE! This is a hard question, and you've done fantastically.

```
> box(4,9,'even')
* * * * * * * * * 
*               * 
*               * 
*     even     * 
*               * 
*               * 
* * * * * * * * *>
```

**Comment by Spencerbrucehudson** [comment]
Ah, gotcha. I actually closed it for that reason. Figured I'd give you a break for the weekend, but much appreciated.

**Comment by willpearse** [comment]
No worries!
